kubejs/constants.js, kubejs/server_scripts/mod_specific/buildinggadgets/buildinggadgets.js
+ fix building gadget as example
=> add constants

kubejs/server_scripts/constants.js, kubejs/server_scripts/mod_specific/mystical_agriculture/ma_crafting.js
- changes MA flight augment to be more expensive 
- adds maInfusion function
=> changes MA flight recipe

kubejs/server_scripts/mod_specific/beyond_earth/beyond_earth.js
Will revert once we can add our own custom recipes
=> Add temp steel recipe

kubejs/server_scripts/mod_specific/beyond_earth/beyond_earth.js
This also fixes a small issue with polymorph
=> Lower Steel Cost

kubejs/data/hostilenetworks/data_models/chicken.json, kubejs/data/hostilenetworks/data_models/ender_slime.json, kubejs/data/hostilenetworks/data_models/glow_squid.json, kubejs/data/hostilenetworks/data_models/mooshroom.json, kubejs/data/hostilenetworks/data_models/sky_slime.json, kubejs/data/hostilenetworks/data_models/squid.json, kubejs/data/hostilenetworks/data_models/terracube.json
Add a few more vanilla passive mobs
And Slimes from Tinkers
=> Add more Hostile Neural Networks Data Models

kubejs/server_scripts/unify.js
Simplify/Unify Ingot Blasting & Smelting from dust and ores
=> Blasting\Smelting Unify

kubejs/server_scripts/mod_specific/mystical_agriculture/ma_crops.js, kubejs/server_scripts/tags.js
add missing MA recipes for cloche
=> Missing Cloche Recipes

config/Mekanism/general.toml, config/artifacts-common.toml, config/inventoryprofilesnext/inventoryprofiles.json, kubejs/server_scripts/constants.js, kubejs/server_scripts/tags.js, kubejs/server_scripts/unify.js
Disallow RS stuff from being boxed by Mek
Add tag to melon slice to fix juice recipe
=> RS doesn't like boxes

config/mysticalagriculture-common.toml, kubejs/server_scripts/harvest.js, kubejs/server_scripts/mod_specific/mystical_agriculture/ma_crafting.js
Brings back a right click harvest that properly uses the primary seed to 'replant' the crop
allows secondary seeds from MA, Closes #744
=> Return of the Right Click

config/inventoryprofilesnext/integrationHints/integrateddynamics.json, config/inventoryprofilesnext/integrationHints/sophisticatedstorage.json, kubejs/server_scripts/harvest.js
Fix interaction with fruit tree leaves with right click harvest
fix inventory profiles buttons for InDy and Sophisticated Storage
=> invprofiles & harvest

kubejs/server_scripts/harvest.js
Has seed/fruit pop out from the face clicked on, better experience for the fruit trees
=> Another small right click harvest change

kubejs/server_scripts/sawmillCompat.js
Compat for Corail Woodcutter, IE Sawmill, Mekanism Sawmill, Create Saw
=> adds sawmill recipes for the different mods

kubejs/server_scripts/unify.js
- remove temp fixes for not having ATO Iridium
- format
=> Ato iridium

.editorconfig, kubejs/data/create/advancements/brass.json, kubejs/server_scripts/mod_specific/mystical_agriculture/ma_crops.js
=> Bugfixes-EQ

kubejs/server_scripts/mod_specific/_allthemods/atm_star.js
=> Fix erroneous 256M component ID

config/ftbquests/quests/chapters/applied_energistics_2.snbt, config/ftbquests/quests/chapters/basic_power_generation.snbt, config/ftbquests/quests/chapters/generating_and_transferring_power.snbt, config/ftbquests/quests/chapters/tips_and_tricks.snbt, config/ftbquests/quests/reward_tables/ae2_basic_reward_table.snbt, config/ftbquests/quests/reward_tables/ae2_basic_rewards.snbt, config/ftbquests/quests/reward_tables/mekanism.snbt
- Rework of AE2 Chapter (courtesy of 6283, or 90 on Discord)
- Added 2 Custom Reward Tables for AE2 to add extra rewards to the quest line
- All "Dimension" Quests have been changed to require an item
- Various Quest Fixes and updates
=> Quest Update v2.4 (Small update)

kubejs/server_scripts/mod_specific/_allthemods/atm_shard.js, kubejs/server_scripts/mod_specific/_allthemods/atm_star.js
blackstone 9x->7x
netherrack 9x->7x
=> Initial Star Tweaks

kubejs/data/occultism/recipes/miner/ancient_debris.json, kubejs/data/occultism/recipes/miner/uraninite_ore.json
Adds both uraninite ore (all varieties at the same random chance) and ancient debris to the dimensional mineshaft.
=> feature: add uraninite and ancient debris to the dimensional mineshaft

config/powah.json5
add soul lava to powah thermo generator
=> Adds Soul Lava to Powah Thermo Generator

config/byg/biomepedia.json5, config/byg/byg-biome-dictionary.json, config/byg/config_versions.json5, config/byg/overworld/biome_selectors/oceans/oceans_1.json5, config/byg/overworld/biome_selectors/oceans/oceans_vanilla.json5, config/byg/overworld/regions/rare_region_1.json5, config/byg/overworld/regions/region_1.json5, config/byg/overworld/regions/region_2.json5, config/byg/overworld/regions/region_3.json5, config/byg/trades.json5
update configs for the new version
=> Update BYG Config

kubejs/server_scripts/tags.js, kubejs/server_scripts/unify.js
Error fix tags
Temp fix thermal press Nuggets until mutant can fix properly
=> misc fixes

config/inventoryprofilesnext/inventoryprofiles.json, kubejs/client_scripts/Jei_tooltips.js, kubejs/data/hostilenetworks/data_models/cow.json, kubejs/data/hostilenetworks/data_models/ender_slime.json, kubejs/data/hostilenetworks/data_models/pig.json, kubejs/data/hostilenetworks/data_models/rabbit.json, kubejs/data/hostilenetworks/data_models/sheep.json, kubejs/data/hostilenetworks/data_models/sky_slime.json, kubejs/data/hostilenetworks/data_models/terracube.json, kubejs/data/industrialforegoing/recipes/laser_drill_fluid/soul_lava.json, kubejs/server_scripts/mod_specific/_allthemods/atm_star.js, kubejs/server_scripts/mod_specific/mystical_agriculture/ma_crops.js, kubejs/server_scripts/tags.js
Turned off "Pickup to inventory"
Added Amethyst bronze seeds to cloche and PI
Add passive mobs back to HNN
Add Tinkers slimes to HNN
Added ATM Shards to ATM Star crafting recipe
Added Teleport pad tooltip
Added Soul Lava to fluid laser drill, catalyst is an ingot of vibranium-allthemodium alloy
=> .27 changes

config/ftbquests/quests/chapters/allthemodium.snbt, config/ftbquests/quests/chapters/basic_power_generation.snbt, config/ftbquests/quests/chapters/forbidden_and_arcanus.snbt, config/ftbquests/quests/chapters/productive_bees.snbt, config/ftbquests/quests/chapters/refined_storage.snbt
- Replaced requirement for "The Other" quest
- Updated requirements for both Jetpack quests
- Updated requirements for the DiamondSight potions
- Fixed formatting issue in the Forbidden & Arcanus starter quest
- All Productive Bee quests should now complete properly (hopefully)
- Fixed typo in Refined Storage quest
=> Various Quest Fixes

kubejs/client_scripts/jei_removals.js, kubejs/server_scripts/unify.js
Added compatibility recipes for the rolling mill because it can only produce a few rods by default
=> Added rod recipes for Rolling Mill

config/ftbquests/quests/chapters/applied_energistics_2.snbt
Adds two new quests for the Bulk Item Cell and Radioactive Chemical Cell.
=> Update AE2 quest chapter for MEGA 1.4.0
